services:
  sensor-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensorsphere-simulator
    restart: unless-stopped
    ports:
      - ${WEB_BIND_ADDRESS:-0.0.0.0}:${WEB_PORT:-8090}:8090
    environment:
      PORT: "8090"
      MQTT_HOST: "${SIMULATOR_MQTT_HOST:-192.168.0.5}"
      MQTT_PORT: "${SIMULATOR_MQTT_PORT:-1883}"
      MQTT_USERNAME: "${SIMULATOR_MQTT_USERNAME:-}"
      MQTT_PASSWORD: "${SIMULATOR_MQTT_PASSWORD:-}"
      MQTT_TOPIC_PREFIX: "${MQTT_TOPIC_PREFIX:-sensors/ble_gateway/ble-gateway-01/sensor}"
      APP_INSTANCE_NAME: "${APP_INSTANCE_NAME:-DEV}"
      DATA_FILE: "/app/data/simulator.json"
    volumes:
      - ./data:/app/data
